#define BLUETEC_VERSION_MAJOR   0xB
#define BLUETEC_VERSION_MINOR   0x066
#define BLUETEC_VERSION         ((BLUETEC_VERSION_MAJOR << 12) | BLUETEC_VERSION_MINOR)
#define BLUETEC_VERSION_LEN     0x02

/* #undef PLATFORM_BRCM */
/* #undef PLATFORM_CSR */
